### ISSUE TITLE
Some players still have "fly" after detaching

### ISSUE THREAD

**Issue by gpcf** [minetest-mods/towercrane#2]
revoking the fly priv doesn't seem to work well, a player abused this on Linuxworks server to get the fly priv for himself.

**Comment by joe7575** [comment]
Are there other mods running which modify the fly privs?
It looks like an interference between two mods.

**Comment by joe7575** [comment]
I found and fixed one bug. A player has retained fly privs after a shutdown/restart or crash of the server.

**Comment by sofar** [comment]
@joe7575 can we close this issue?

**Comment by joe7575** [comment]
I fixed one real bug but got no feedback from the opener so far.
But for me it's closed.

**Comment by daytonnvpaul** [comment]
I didn't have a 're-open' button.  I have the same issue when a player is in a shared area.  Their partner removed the tower spawner, and they have fly privs until I revoke it.

More detail.  Player places the spawner, uses the switch, then they dig the switch instead of deactivating it.

Whodathunk that players would ever look for an exploit in a tool.  :)

Server 5.2.0-dev

**Comment by joe7575** [comment]
Thanks for your report. But I did not understand it yet. How do you dig the switch, when the crane is on? This node is unbreakable.

**Comment by daytonnvpaul** [comment]
I'm trying to get more details from the players, however its a holiday weekend here.

After they reported this to me, and they had removed the tower crane, yet still had fly privs.  I revoked their fly priv (2 different players), and they stated they couldn't place the tower spawner again.  The both tried again after leaving and rejoining the game.

I'm also using the mp_xtraores mod (old version), which has some tools that seem to be able to break nodes that would otherwise, be unbreakable.

I'm trying to duplicate the situation with a test account, and will advise you of my results in a day or 2.

Thanks for looking into this.

**Comment by daytonnvpaul** [comment]
Here's the method my players have found.

After building the tower crane, and activating it, they accidentally dig the switch with either an mp-xtraores drill, or a technic drill.  at that time, they have perm fly privs.  However, they can no longer activate another tower switch.  Neither on or off.

My workaround is to have the player completely empty their personal inventory, log out, and then i use the remove_player command on them.

It seems as if the tower data is stored in the player data.  I'm not a coder, so I could be totally incorrect.

I'm using the sqlite3 player backend on a 5.2.0-dev server

**Comment by joe7575** [comment]
There is normally a good reason to make nodes undiggable. To give players the rights to remove undiggable nodes is always a bad idea. 
But anyhow, in this case I was able to make a bugfix.
Please try it an let me know, if it works.

**Comment by daytonnvpaul** [comment]
For what its worth. it is the other mods that interfere with dig properties of nodes, not the admins -- at least not in this case.

I will install the update, and let you know within 2 days, end of weekend by the latest.

**Comment by daytonnvpaul** [comment]
Looks like everything is working as intended.  Thanks for you response and fix.  Feel free to close this issue.
