### ISSUE TITLE
Privs not being restored

### ISSUE THREAD

**Issue by daytonnvpaul** [minetest-mods/towercrane#7]
If a player has been granted fast and/or fly before operating the tower crane, they lose it on deactivation.  Moderators, which are granted that priv as well as protection_bypass, also lose their fast and fly privs if they deactivate the tower crane, overriding the player's action.

**Comment by hlqkj** [comment]
Had the same issue. By playing a bit with the source code i found out that the `reset_operator_privs()` function gets called twice after the player switches off the crane - hence the second time the privs are lost because the first run clears them from the player metadata.

By adding a `debug.traceback()` at the beginning of `reset_operator_privs()` I noticed that the first call is correctly done by the `on_rightclick` callback but a second call is made by a `minetest.after`, very possibly the one at [control.lua#L218](https://github.com/minetest-mods/towercrane/blob/5bcd049924a1cac697273c298372642e6b0c47af/control.lua#L218), causing the 2nd call from [control.lua#L233](https://github.com/minetest-mods/towercrane/blob/5bcd049924a1cac697273c298372642e6b0c47af/control.lua#L223).

**Comment by joe7575** [comment]
Sorry for the delay, I just happened to come over here. I don't get notifications (I don't know why) Should be fixed now.
